import os

DEFAULT_SOURCE_LANG = "auto"
DEFAULT_TARGET_LANG = "vi"
DEFAULT_WHISPER_MODEL = "base"
DEFAULT_TRANSLATE_ENGINE = "google"
DEFAULT_SUBTITLE_STYLE = "default"
DEFAULT_VIDEO_QUALITY = "best[height<=1080]"
DEFAULT_AUDIO_QUALITY = "bestaudio/best"
DEFAULT_OUTPUT_DIR = "output"
DEFAULT_TEMP_DIR = "temp"
DEFAULT_DOWNLOAD_DIR = "downloads"

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
DEEPSEEK_API_KEY = os.getenv("DEEPSEEK_API_KEY", "")
